# Generated by Django 4.2.2 on 2023-06-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='folder',
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_folder', to='artkiveapi.folder'),
        ),
    ]
