# Generated by Django 4.2.2 on 2023-06-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0002_remove_image_folder_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='artkiveapi.ImageTag', to='artkiveapi.tag'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artkiveapi.tag'),
        ),
    ]
