# Generated by Django 4.2.2 on 2023-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0002_folder_image_tag_imagetag_imagefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folders',
            field=models.ManyToManyField(through='artkiveapi.ImageFolder', to='artkiveapi.folder'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(through='artkiveapi.ImageTag', to='artkiveapi.tag'),
        ),
    ]
