# Generated by Django 4.2.2 on 2023-06-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0003_image_folders_image_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artkiveapi.muser'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='bio',
            field=models.CharField(max_length=100),
        ),
    ]
