# Generated by Django 4.2.2 on 2023-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0004_remove_folder_user_folder_creator_alter_muser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='folders',
            field=models.ManyToManyField(related_name='images', through='artkiveapi.ImageFolder', to='artkiveapi.folder'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(related_name='images', through='artkiveapi.ImageTag', to='artkiveapi.tag'),
        ),
    ]
