# Generated by Django 4.2.2 on 2023-06-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0006_remove_image_folders_remove_image_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artkiveapi.muser'),
        ),
    ]
