# Generated by Django 4.2.2 on 2023-06-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0007_alter_folder_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_folder', to='artkiveapi.folder'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tag', to='artkiveapi.tag'),
        ),
    ]
