# Generated by Django 4.2.2 on 2023-06-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artkiveapi', '0008_alter_imagefolder_folder_alter_imagetag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='muser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artkiveapi.muser'),
            preserve_default=False,
        ),
    ]
